### ISSUE TITLE
Cara Ganti Icon Lonceng Yang Di sebelah Kode Marquee

### ISSUE THREAD

**Issue by BerkasKita** [BerkasKita/123-Movies-Clone#1]
# Preview
<img alt="Rasgane" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjFh2FgIZHCbaKcVvM8d1c4PX5w4mlanJ3Lcc6bIILIiKVmb_O-_1L8TRRSv5kHjpNa1Y8A1vnZjMRFbnX6jAHUgKFW4O7-gVzxXYVuF-jff79E-B7F5PimDyG8gkm2y8XiIT9zKPGHao6IEQ0zX-78a9iuq4_q50yHFVZtwbiAfYl3QLcYtvs0KHwG3eok/s0/jhgkjhjgdfijgdfojgdfjghksjdfghjksdfhgjksdfhgjkdfhgjkdf.jpg" loading="lazy">

# Langkah-Langkah
+ Cari kode css ini

  ```css
  .container_marquee .boxInformasi:before{position:absolute;content:'\f0f3';font-family:'Font Awesome 6 Free';color:#f5cc2a;font-size:24px;font-weight:600;text-align:center;display:inline-block;width:50px;height:50px;top:0;left:0;animation:ring 2.5s infinite}
  ```
+ Pada `content: '\f0f3';` ganti `\f0f3` dengan text kamu.
+ Atur `height: 50px;` ganti pada `50px` sesuaikan dengan panjang text.
+ Cari kode css ini

  ```css
  .container_marquee .boxInformasi marquee {
      color: #e2e2e2;
      margin: 0 50px;
  }
  ```
+ Ganti `margin: 0 50px;` menjadi ` margin: 0 50px 0 Ukuran_height;`
